BWTOOL = "bwtool"
DNASHAPEINTER = {'HelT': (30.94, 38.05), 'MGW': (2.85, 6.20),
                 'ProT': (-16.51, -0.03), 'Roll': (-8.57, 8.64)}
# FEATURE VECTOR TYPE CONSTANTS
SEQ_AND_DNA_SHAPE_TYPE_CONSTANT = 0
DNA_SHAPE_ONLY_TYPE_CONSTANT = 1
DNA_SHAPE_AND_FLEX_TYPE_CONSTANT = 2
DNA_SHAPE_FEATURE_TYPE_CONSTANTS = {SEQ_AND_DNA_SHAPE_TYPE_CONSTANT, DNA_SHAPE_ONLY_TYPE_CONSTANT, DNA_SHAPE_AND_FLEX_TYPE_CONSTANT}
# SEQUENCE FEATURE TYPE CONSTANTS
PSSM_SCORE_TYPE_CONSTANT = 0
TFFM_SCORE_TYPE_CONSTANT = 1
BINARY_ENCODING_TYPE_CONSTANT = 2

